source 'https://rubygems.org'
gem 'rails', '4.2.5.2'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'redcarpet', '~> 3.3', '>= 3.3.4'
gem 'react-rails', '~> 1.6.2'
gem 'autoprefixer-rails'
gem 'rails-bootstrap-markdown'
gem 'bootstrap_form'
gem 'bcrypt-ruby', :require=>'bcrypt'

gem 'sdoc', '~> 0.4.0', group: :doc
group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'sqlite3'
  gem 'faker', '~> 1.6', '>= 1.6.3'
end
group :production do
  gem 'pg', '~> 0.15'
end
